apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: monitoring
  labels:
    type: nfs
    app: mysql-deployment
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.27.59.199
    path: "/drive/data"
