apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-mysql
  namespace: monitoring
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

