apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: mysql-exporter
spec:
  #  serviceName: mysqld-exporter-service
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 9104
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DATA_SOURCE_NAME
              value: "root:$(MYSQL_ROOT_PASSWORD)@(mysql:3306)/"
            - name: collect.global_status
              value: 'true'
            - name: collect.info_schema.innodb_metrics
              value: 'true'
            - name: collect.auto_increment.columns
              value: 'true'
            - name: collect.info_schema.processlist
              value: 'true'
            - name: collect.binlog_size
              value: 'true'
            - name: collect.info_schema.tablestats
              value: 'true'
            - name: collect.global_variables
              value: 'true'
            - name: collect.info_schema.query_response_time
              value: 'true'
            - name: collect.info_schema.userstats
              value: 'true'
            - name: collect.info_schema.tables
              value: 'true'
            - name: collect.perf_schema.tablelocks
              value: 'true'
            - name: collect.perf_schema.file_events
              value: 'true'
            - name: collect.perf_schema.eventswaits
              value: 'true'
            - name: collect.perf_schema.indexiowaits
              value: 'true'
            - name: collect.perf_schema.tableiowaits
              value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: mysql-exporter
  labels:
    app: mysql-exporter
spec:
  ports:
    - port: 9104
      targetPort: 9104
      protocol: TCP
  selector:
    app: mysql-exporter
  type: ClusterIP
